apiVersion: v1
kind: Pod
metadata:
  name: ciscozeus-logforwarder
  namespace: kube-system
spec:
  containers:
    - name: ciscozeus-logforwarder
      image: kumulustech/td-agent-cz:latest
      env:
        - name: user
          value: NOUSER
        - name: token
          value: NOTOKEN
        - name: shared_key
          value: cisco_zeus_log_metric_pipline
        - name: self_hostname
          value: fluentd-client1.ciscozeus.io
        - name: data_server
          value: data01.ciscozeus.io
        - name: master
          value: MASTER
        - name: api_version
          value: 1.3
      volumeMounts:
        - mountPath: /var/run
          name: varrun
        - mountPath: /var/lib/docker/containers
          name: containerlogs
        - mountPath: /varlog
          name: varlog
  Volumes:
    - hostPath:
        path: /var/run
      name: varrun
    - hostPath:
        path: /var/lib/docker/containers
      name: containerlogs
    - hostPath:
        path: /var/log
      name: varlog
