apiVersion: v1
kind: Pod
metadata:
  name: ciscozeus-logforwarder
  namespace: kube-system
spec:
  containers:
    - name: ciscozeus-logforwarder
      image: kumulus/td-agent
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /var/lib/docker/containers
          name: containerlogs
        - mountPath: /varlog
          name: varlog
  Volumes:
    - hostPath:
        path: /var/run/docker.sock
      name: dockersock
    - hostPath:
        path: /var/lib/docker/containers
      name: containerlogs
    - hostPath:
        path: /var/log
      name: varlog
